name: Build and generate Android application

on:
  push:
    branches:
      - master
      - feature/**
  pull_request:
    branches:
      - master
      - feature/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Generate APK
      run: ./gradlew assembleDebug
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: enotes-build
        path: app/build/outputs/apk/debug/
